// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcDZFgbP7XUifXb-zb5g-AvH1iPR2HaP4',
    appId: '1:635305520200:web:6c6c136aa05ff13af73c7d',
    messagingSenderId: '635305520200',
    projectId: 'barbershop-gentleman',
    authDomain: 'barbershop-gentleman.firebaseapp.com',
    storageBucket: 'barbershop-gentleman.firebasestorage.app',
    measurementId: 'G-75V0GQMVLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO7rE5JAxDS3xbucCe544f0i0lers4QAo',
    appId: '1:635305520200:android:2dd15d19739e761ef73c7d',
    messagingSenderId: '635305520200',
    projectId: 'barbershop-gentleman',
    storageBucket: 'barbershop-gentleman.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnueMtezaIP2KxDIIYKZznAZQVz0jp7uQ',
    appId: '1:635305520200:ios:89aa5979171d0aaff73c7d',
    messagingSenderId: '635305520200',
    projectId: 'barbershop-gentleman',
    storageBucket: 'barbershop-gentleman.firebasestorage.app',
    iosBundleId: 'com.example.barberShopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnueMtezaIP2KxDIIYKZznAZQVz0jp7uQ',
    appId: '1:635305520200:ios:89aa5979171d0aaff73c7d',
    messagingSenderId: '635305520200',
    projectId: 'barbershop-gentleman',
    storageBucket: 'barbershop-gentleman.firebasestorage.app',
    iosBundleId: 'com.example.barberShopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcDZFgbP7XUifXb-zb5g-AvH1iPR2HaP4',
    appId: '1:635305520200:web:fb3391bffa0a8d0bf73c7d',
    messagingSenderId: '635305520200',
    projectId: 'barbershop-gentleman',
    authDomain: 'barbershop-gentleman.firebaseapp.com',
    storageBucket: 'barbershop-gentleman.firebasestorage.app',
    measurementId: 'G-KR9E7QTYYF',
  );
}
